from .nodes import (
    SamplerGeneratorNode,
    SchedulerGeneratorNode,
    ModelGeneratorNode,
    DiffusionModelGeneratorNode,
    AnyAdapterNode,
    CheckpointSelectorNode,
    DiffusionModelSelectorNode,
    VAEGeneratorNode,
    TextEncoderGeneratorNode,
    VAESelectorNode,        
    TextEncoderSelectorNode,
    StringToIntNode,          
    StringToFloatNode,
    TextConcatNode,
    LORASelectorNode,
    ClipSkipSliderNode,
    PonyPrefixesNode,
    ImageResizeNode,
    ResizeMethodControlNode,
    ResizeInterpolationControlNode,
    AnyConcatNode,
    OptionalCondMergeNode,
    ScaleImageAspectNode,
    MaskDebugNode,
    ShiftSliderNode,
    DA_Base_KSampler,
    DA_Enhanced_KSampler,
    LoadImageWithMetadataNode,
    MyXYZHelper,
    MyXYGridAccumulator,
    MyXYZSuperStacker,
    ListCreaterNode,
    CountListNode,
    AnytoIntegerAdapterNode,
    AnytoFloatAdapterNode,
    SamplerSelectorFromStringNode,
    SchedulerSelectorFromStringNode,
    ListRerouteNode,
)

NODE_CLASS_MAPPINGS = {
    "SamplerGeneratorNode": SamplerGeneratorNode,
    "SchedulerGeneratorNode": SchedulerGeneratorNode,
    "ModelGeneratorNode": ModelGeneratorNode,
    "DiffusionModelGeneratorNode": DiffusionModelGeneratorNode,
    "AnyAdapterNode": AnyAdapterNode,
    "CheckpointSelectorNode": CheckpointSelectorNode,
    "DiffusionModelSelectorNode": DiffusionModelSelectorNode,
    "VAEGeneratorNode": VAEGeneratorNode, 
    "TextEncoderGeneratorNode": TextEncoderGeneratorNode,
    "VAESelectorNode": VAESelectorNode,
    "TextEncoderSelectorNode": TextEncoderSelectorNode,
    "StringToIntNode": StringToIntNode,
    "StringToFloatNode": StringToFloatNode,
    "TextConcatNode": TextConcatNode,
    "LORASelectorNode": LORASelectorNode,
    "ClipSkipSliderNode": ClipSkipSliderNode,
    "PonyPrefixesNode": PonyPrefixesNode,
    "ImageResizeNode": ImageResizeNode,
    "ResizeMethodControlNode": ResizeMethodControlNode,
    "ResizeInterpolationControlNode": ResizeInterpolationControlNode,
    "AnyConcatNode": AnyConcatNode,
    "OptionalCondMergeNode": OptionalCondMergeNode,
    "ScaleImageAspectNode": ScaleImageAspectNode,
    "MaskDebugNode": MaskDebugNode,
    "ShiftSliderNode": ShiftSliderNode,
    "DA_Base_KSampler": DA_Base_KSampler,
    "DA_Enhanced_KSampler": DA_Enhanced_KSampler,
    "LoadImageWithMetadataNode": LoadImageWithMetadataNode,
    "MyXYZHelper": MyXYZHelper,
    "MyXYGridAccumulator": MyXYGridAccumulator,
    "MyXYZSuperStacker": MyXYZSuperStacker,
    "ListCreaterNode":ListCreaterNode,
    "CountListNode" : CountListNode,
    "AnytoIntegerAdapterNode": AnytoIntegerAdapterNode,
    "AnytoFloatAdapterNode": AnytoFloatAdapterNode,
    "SamplerSelectorFromStringNode": SamplerSelectorFromStringNode,
    "SchedulerSelectorFromStringNode": SchedulerSelectorFromStringNode,
    "ListRerouteNode": ListRerouteNode,
}

NODE_DISPLAY_NAME_MAPPINGS = {
    "SamplerGeneratorNode": "Dynamic Sampler Selector",
    "SchedulerGeneratorNode": "Dynamic Scheduler Selector",
    "ModelGeneratorNode": "Dynamic Checkpoint Selector",
    "DiffusionModelGeneratorNode": "Dynamic Diffusion Model Selector",
    "AnyAdapterNode": "Any‑to‑Any Adapter",
    "СheckpointSelectorNode": "Checkpoint Selector",
    "DiffusionModelSelectorNode": "Diffusion Model Selector",
    "VAEGeneratorNode": "Dynamic VAE Selector",
    "TextEncoderGeneratorNode": "Dynamic Encoder Selector",
    "VAESelectorNode": "VAE Selector",
    "TextEncoderSelectorNode": "Text Encoder Selector",
    "StringToIntNode": "String to Integer",
    "StringToFloatNode": "String to Float",
    "TextConcatNode": "Text Concatenator",
    "LORASelectorNode": "Dynamic LORA Selector",
    "ClipSkipSliderNode": "Clip Skip Slider",
    "PonyPrefixesNode": "Rating, Score, Source for Pony",
    "ImageResizeNode": "Image and Mask Resize",
    "ResizeMethodControl": "ResizeMethodControl",
    "ResizeInterpolationControlNode": "ResizeInterpolationControl",
    "AnyConcatNode": "Any Concat",
    "OptionalCondMergeNode": "Optional Conditioning Merge",
    "ScaleImageAspectNode": "Scale Image",
    "MaskDebugNode": "Mask Debug",
    "ShiftSliderNode": "Shift Slider",
    "DA_Base_KSampler": "DA_Base_KSampler",
    "DA_Enhanced_KSampler": "DA_Enhanced_KSampler",
    "LoadImageWithMetadataNode": "Load Image With Metadata",
    "MyXYZHelper": "MyXYZHelper",
    "MyXYGridAccumulator": "MyXYGridAccumulator",
    "MyXYZSuperStacker": "MyXYZSuperStacker",
    "ListCreaterNode": "List Creater",
    "CountListNode": "Count List",
    "AnytoIntegerAdapterNode": "Any to Integer",
    "AnytoFloatAdapterNode": "Any to Float",
    "SamplerSelectorFromStringNode": "Sampler Selector From String",
    "SchedulerSelectorFromStringNode": "Scheduler Selector From String",
    "ListRerouteNode": "List Reroute",
}
