from .nodes import (
    ConditionalVAEDecodePreview,
    DA_BusInNode,
    DA_BusOutNode,
    DA_LatentLoader,
    MultiPlaceholderPromptList,
    OptionalCondMergeNode,
    PatchModelSelectorNode,
    
)

from .adapters import (
    AnyAdapterNode,
    AnyConcatNode,
    AnytoIntegerAdapterNode,
    AnytoFloatAdapterNode,
    StringToAnyNode,
    StringToIntNode,
    StringToFloatNode,
    TextConcatNode,
)

from .debug_tools import (
    DA_AudioDebugNode,
    MaskDebugNode,
)
from .image_utilites import (
    ImageResizeNode,
    LoadImageWithMetadataNode,
    ResizeMethodControlNode,
    ResizeInterpolationControlNode,
    SaveImageNoMetaNode, 
)

from .other_list_tools import (
    CountListNode,
    ListCreaterNode,
    ListRerouteNode,
    ListCombinerNode,
)

from .ksamplers import (
    DA_Base_KSampler,
    DA_Enhanced_KSampler,
    DA_TiledUpscaler,
    
)

from .other_selectors import (
    BooleanSwitchNode,
    ClipSkipSliderNode,
    FloatSelectorNode,
    PonyPrefixesNode,
    ShiftSliderNode,
    WanNumFramesNode,
)

from .xyz_plot import (
    MyXYZHelper,
    MyXYGridAccumulator,
    MyXYZSuperStacker,
    XYZConflictValidatorAndSwitch,
)

from .xyz_selectors_and_generators import (
    CheckpointSelectorNode,
    DiffusionModelGeneratorNode,
    DiffusionModelSelectorNode,
    LORASelectorNode,
    ModelGeneratorNode,
    SamplerSelectorFromStringNode,
    SamplerGeneratorNode,
    SchedulerSelectorFromStringNode,
    SchedulerGeneratorNode,
    TextEncoderSelectorNode,
    TextEncoderGeneratorNode,
    VAEGeneratorNode,
    VAESelectorNode,
)

NODE_CLASS_MAPPINGS = {
    "AnyAdapterNode": AnyAdapterNode,
    "AnyConcatNode": AnyConcatNode,
    "AnytoIntegerAdapterNode": AnytoIntegerAdapterNode,
    "AnytoFloatAdapterNode": AnytoFloatAdapterNode,
    "BooleanSwitchNode": BooleanSwitchNode,
    "CheckpointSelectorNode": CheckpointSelectorNode,
    "ClipSkipSliderNode": ClipSkipSliderNode,
    "ConditionalVAEDecodePreview": ConditionalVAEDecodePreview,
    "CountListNode": CountListNode,
    "DA_AudioDebugNode": DA_AudioDebugNode,
    "DA_Base_KSampler": DA_Base_KSampler,
    "DA_BusInNode": DA_BusInNode,
    "DA_BusOutNode": DA_BusOutNode,
    "DA_Enhanced_KSampler": DA_Enhanced_KSampler,
    "DA_LatentLoader": DA_LatentLoader,
    "DA_TiledUpscaler": DA_TiledUpscaler,
    "DiffusionModelGeneratorNode": DiffusionModelGeneratorNode,
    "DiffusionModelSelectorNode": DiffusionModelSelectorNode,
    "ImageResizeNode": ImageResizeNode,
    "FloatSelectorNode": FloatSelectorNode,
    "ListCombinerNode": ListCombinerNode,
    "ListCreaterNode": ListCreaterNode,
    "ListRerouteNode": ListRerouteNode,
    "LoadImageWithMetadataNode": LoadImageWithMetadataNode,
    "LORASelectorNode": LORASelectorNode,
    "MaskDebugNode": MaskDebugNode,
    "ModelGeneratorNode": ModelGeneratorNode,
    "MultiPlaceholderPromptList": MultiPlaceholderPromptList,
    "MyXYZHelper": MyXYZHelper,
    "MyXYGridAccumulator": MyXYGridAccumulator,
    "MyXYZSuperStacker": MyXYZSuperStacker,
    "OptionalCondMergeNode": OptionalCondMergeNode,
    "PatchModelSelectorNode": PatchModelSelectorNode,
    "PonyPrefixesNode": PonyPrefixesNode,
    "ResizeInterpolationControlNode": ResizeInterpolationControlNode,
    "ResizeMethodControlNode": ResizeMethodControlNode,
    "SamplerGeneratorNode": SamplerGeneratorNode,
    "SamplerSelectorFromStringNode": SamplerSelectorFromStringNode,
    "SaveImageNoMetaNode": SaveImageNoMetaNode, 
    "SchedulerGeneratorNode": SchedulerGeneratorNode,
    "SchedulerSelectorFromStringNode": SchedulerSelectorFromStringNode,
    "ShiftSliderNode": ShiftSliderNode,
    "StringToAnyNode": StringToAnyNode,
    "StringToIntNode": StringToIntNode,
    "StringToFloatNode": StringToFloatNode,
    "TextConcatNode": TextConcatNode,
    "TextEncoderGeneratorNode": TextEncoderGeneratorNode,
    "TextEncoderSelectorNode": TextEncoderSelectorNode,
    "VAEGeneratorNode": VAEGeneratorNode, 
    "VAESelectorNode": VAESelectorNode,
    "WanNumFramesNode": WanNumFramesNode,
    "XYZConflictValidatorAndSwitch": XYZConflictValidatorAndSwitch,
}

NODE_DISPLAY_NAME_MAPPINGS = {
    "AnyAdapterNode": "Any‑to‑Any Adapter",
    "AnyConcatNode": "Any Concat",
    "AnytoIntegerAdapterNode": "Any to Integer",
    "AnytoFloatAdapterNode": "Any to Float",
    "BooleanSwitchNode": "Boolean Switch",
    "CheckpointSelectorNode": "Checkpoint Selector",
    "ClipSkipSliderNode": "Clip Skip Slider",
    "ConditionalVAEDecodePreview": "Conditional VAE Decode Preview",
    "CountListNode": "Count List",
    "DA_AudioDebugNode": "DA_AudioDebug",
    "DA_Base_KSampler": "DA_Base_KSampler",
    "DA_BusInNode": "BusIn",
    "DA_BusOutNode": "BusOut",
    "DA_Enhanced_KSampler": "DA_Enhanced_KSampler",
    "DA_LatentLoader": "Latent Loader",
    "DA_TiledUpscaler": "Tiled Upscaler (experemental)",
    "DiffusionModelGeneratorNode": "Dynamic Diffusion Model Selector",
    "DiffusionModelSelectorNode": "Diffusion Model Selector",
    "ImageResizeNode": "Image and Mask Resize",
    "FloatSelectorNode": "Float Selector (legacy)",
    "ListCombinerNode": "List Combiner",
    "ListCreaterNode": "List Creater",
    "ListRerouteNode": "List Reroute",
    "LoadImageWithMetadataNode": "Load Image With Metadata",
    "LORASelectorNode": "Dynamic LORA Selector",
    "MaskDebugNode": "Mask Debug",
    "ModelGeneratorNode": "Dynamic Checkpoint Selector",
    "MultiPlaceholderPromptList": "MultiPlaceholder Prompt List",
    "MyXYZHelper": "MyXYZHelper",
    "MyXYGridAccumulator": "MyXYGridAccumulator",
    "MyXYZSuperStacker": "MyXYZSuperStacker",
    "OptionalCondMergeNode": "Optional Conditioning Merge",
    "PatchModelSelectorNode": "Patch Model Selector",
    "PonyPrefixesNode": "Rating, Score, Source for Pony",
    "ResizeInterpolationControlNode": "ResizeInterpolationControl",
    "ResizeMethodControlNode": "ResizeMethodControl",
    "SamplerGeneratorNode": "Dynamic Sampler Selector",
    "SamplerSelectorFromStringNode": "Sampler Selector From String",
    "SaveImageNoMetaNode": "Save Image With No Meta", 
    "ScaleImageAspectNode": "Scale Image", 
    "SchedulerGeneratorNode": "Dynamic Scheduler Selector",
    "SchedulerSelectorFromStringNode": "Scheduler Selector From String",
    "ShiftSliderNode": "Shift Slider",
    "StringToAnyNode": "String To Any",
    "StringToIntNode": "String to Integer",
    "StringToFloatNode": "String to Float",
    "TextConcatNode": "Text Concatenator",
    "TextEncoderGeneratorNode": "Dynamic Encoder Selector",
    "TextEncoderSelectorNode": "Text Encoder Selector",
    "VAEGeneratorNode": "Dynamic VAE Selector", 
    "VAESelectorNode": "VAE Selector",
    "WanNumFramesNode": " Wan Number of Frames",
    "XYZConflictValidatorAndSwitch": "XYZ ConflictValidator And Switch",
}
