[project]
name = "demonalone-nodes-comfyui"
description = "A collection of nodes designed to provide mostly dynamic dropdown selectors for Samplers, Schedulers, Checkpoints, and Diffusion Models, outputting a comma-separated string intended for use in XYZ plots. It also contains some additional nodes suitable for a wide range of applications"
version = "4.1.8"
license = {file = "LICENSE"} 
# classifiers = [
#     "Environment :: GPU :: NVIDIA CUDA",    # NVIDIA CUDA support
# ]


[project.urls]
Repository = "https://github.com/DemonAlone/DemonAlone-nodes-ComfyUI"
#  Used by Comfy Registry https://registry.comfy.org
"Bug Tracker" = "https://github.com/DemonAlone/DemonAlone-nodes-ComfyUI/issues"

[tool.comfy]
PublisherId = "demonalone"
DisplayName = "DemonAlone-nodes-ComfyUI"
Icon = "https://avatars.githubusercontent.com/u/25270760"
includes = [] 
# "requires-comfyui" = ">=1.0.0"  # ComfyUI version compatibility
